- hosts: my_windows_pc
  tasks:
  - name: Warn logged in users of impending upgrade
    win_msg:
      display_seconds: 60
      msg: A Windows upgrade is about to start, please save unsaved work and DO NOT TURN OFF THE PC!!!!
  - name: tell the users to save unsaved work
    win_say:
      msg:  A Windows upgrade is about to start, please save unsaved work and DO NOT TURN OFF THE PC!!!!
  - name: mount the upgrade iso if the system requires it
    win_disk_image:
      image_path: \\\\DAGON-PC\\myshare\\client\\'windows upgrade'\\Windows10eng.iso
      state: present
    when: ansible_distribution_version != "10.0.18363.1"  
 # - name: german slution , map and run updates
 #   raw: "net use K: \\\\DAGON-PC\\myshare\\client /persistent:no; cmd /c k:\\cmd\\DoUpdate.cmd"
 #   register: command_result
 #   changed_when: "'Installation successful' in command_result.stdout"
 #   failed_when:
 #     - "'Nothing to do' not in command_result.stdout"
 #     - "'Installation successful.' not in command_result.stdout"
 # - name: copy log file to log directory on the server
 #   win_shell: "net use K: '\\\\DAGON-PC\\myshare\\client' /persistent:no;  cp -path 'c:\\windows\\wsusofflineupdate.log' -destination 'k:\\updateslogs\\{{ inventory_hostname }}.log' -force"
